### ISSUE TITLE
Equation inserting does not work

### ISSUE THREAD

**Issue by beautylix** [arjunsuresh/ckeditor-Q2A#1]
I installed your mathjax plugin and this plugin, configured as you stated, but it does not work

When I enter equations, it does not show as equations, it shows as text in editor and website

How to fix it?

**Comment by arjunsuresh** [comment]
Hi, can you give me a link to your website?

**Comment by beautylix** [comment]
I am sorry I just tested in my localhost

**Comment by arjunsuresh** [comment]
oh okay. You can see the source of a question page and see it the "mathjax" url part is there. By default mathjax is enabled only on question pages. For others, you can add the MathJax widget from Admin/Layout.

**Comment by beautylix** [comment]
Thanks a lot, I have solved, I placed mathjax under ckeditor folder before, it should be in qa-plugin folder, it works well now.
